name: Hello World

on: push

jobs:
  hello-world:
    name: Say Hello World
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Rasmus
        MIDDLE_NAME: Karlsson
        LAST_NAME: Källqvist
      run: |
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
